### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yusmiatiliau** [scottlab/ALEC#2]
Hi There,

I recently tried this tool to correct oxford nanopore reads:
my command was:
"/media/WORKSPACE/cen/ALEC/ALEC/ALEC.py" -r "/media/WORKSPACE/cen/cyp2c19-0-211_formated.fasta" -i "/media/WORKSPACE/cen/totallibrary_sam_bam_output/barcode01_c1927sorted.sam.bam" -t CYP2C19-2-7:0-212 -del 0.04 -ins 0.05 -mis 0.06 -del_hp 0.04 -ins_hp 0.05 -x nanopore

it gave me this error below. Can you please enlighten me what's wrong here.

Thanks a lot,

Cen

Namespace(del_homo_p=0.06, deletion=0.3, downsample_freq=1.0, input='/media/WORKSPACE/cen/totallibrary_sam_bam_output/barcode01_c1927sorted.sam.bam', ins_homo_p=0.05, insert=0.2, lengthFilter=0.0, mismatch=0.2, platform='nanopore', reference='/media/WORKSPACE/cen/cyp2c19-0-211_formated.fasta', targetRegion='CYP2C19-2-7:0-212')
#################################################################################
Correcting reads in regionCYP2C19-2-7:0-212
Traceback (most recent call last):
  File "/media/WORKSPACE/cen/ALEC/ALEC/ALEC.py", line 494, in <module>
    main()
  File "/media/WORKSPACE/cen/ALEC/ALEC/ALEC.py", line 482, in main
    parse_fasta(args.reference)
  File "/media/WORKSPACE/cen/ALEC/ALEC/ALEC.py", line 73, in parse_fasta
    region_start = int(args.targetRegion[args.targetRegion.find(":")+1:args.targetRegion.find("-")])
ValueError: invalid literal for int() with base 10: ''

**Comment by mssmyangyao** [comment]
Please try to remove '-' in chromosome ID of your customized reference.

**Comment by yusmiatiliau** [comment]
Forgot to mention, Yes, I've tried that already, it gave me this error:
Correcting reads in regionCYP2C1927:0-212
Traceback (most recent call last):
  File "/media/WORKSPACE/cen/ALEC/ALEC/ALEC.py", line 494, in <module>
    main()
  File "/media/WORKSPACE/cen/ALEC/ALEC/ALEC.py", line 483, in main
    load_input_file()
  File "/media/WORKSPACE/cen/ALEC/ALEC/ALEC.py", line 471, in load_input_file
    samfile = pysam.AlignmentFile(args.input,"r")
AttributeError: 'module' object has no attribute 'AlignmentFile'

**Comment by mssmyangyao** [comment]
You need to update your pysam module.
