### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Bilcag** [scottlab/ALEC#3]
Hello,

I am trying this tool to correct oxford nanopore reads with this command:

`Python ALEC.py -r /Users/bilcag/bin/b37/human_g1k_v37.fa -i /Users/bilcag/Desktop/Nanopore/Gridion_CFTR_2D_15-03-18/aln_3.sam -t 7:117242085-117252410 -x nanopore`

But it gave me this error below. Could you please help me about the problem?

> Namespace(del_homo_p=0.06, deletion=0.3, downsample_freq=1.0, input='/Users/bilcag/Desktop/Nanopore/Gridion_CFTR_2D_15-03-18/aln_3.sam', ins_homo_p=0.0, insert=0.2, lengthFilter=0.0, mismatch=0.2, platform='nanopore', reference='/Users/bilcag/bin/b37/human_g1k_v37.fa', targetRegion='7:117242085-117252410')
> #################################################################################
> Correcting reads in region7:117242085-117252410
> ALEC took 0.0 seconds to get reference info
> ALEC took 0.0 seconds to get reads
> Traceback (most recent call last):
>   File "ALEC.py", line 494, in <module>
>     main()
>   File "ALEC.py", line 488, in main
>     cor_reads = correct_reads(reads)
>   File "ALEC.py", line 424, in correct_reads
>     allele_freq_lst,consensus_base,depth = get_allele_freq_lst(base_matrix)
>   File "ALEC.py", line 175, in get_allele_freq_lst
>     allele_freq = [A_ct/total_ct,T_ct/total_ct,C_ct/total_ct,G_ct/total_ct,D_ct/total_ct]
> ZeroDivisionError: float division by zero

Additionally, I used Albacore (2.1.3) for basecelling and BWA-MEM (0.7.15-r1140) for mapping. And I updated both pysam and numpy. Python version is below:

> Python 2.7.14 |Anaconda, Inc.| (default, Oct  5 2017, 02:28:52) 
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.

Thank you!

Bilcag

**Comment by mssmyangyao** [comment]
Hi Bilcag,

Is your library constructed with PCR amplicons. If yes, please use exact genome coordinates of your PCR product as  targetRegion.

Let me if it works.

Best,

Yao

________________________________

**Comment by Bilcag** [comment]
Thank you so much!

I tried your recommendations and the error solved. But the script gave another error now.

> Namespace(del_homo_p=0.06, deletion=0.3, downsample_freq=1.0, input='/Users/bilcag/Desktop/Nanopore/Gridion_CFTR_2D_15-03-18/alignment.bam', ins_homo_p=0.0, insert=0.2, lengthFilter=0.0, mismatch=0.2, platform='nanopore', reference='/Users/bilcag/bin/hg19/hg19.fasta', targetRegion='chr7:117242825-117251897')
> #################################################################################
> Correcting reads in regionchr7:117242825-117251897
> ALEC took 0.0 seconds to get reference info
> ALEC took 0.0 seconds to get reads
> Traceback (most recent call last):
>   File "/Users/bilcag/ALEC-master/ALEC/ALEC.py", line 494, in <module>
>     main()
>   File "/Users/bilcag/ALEC-master/ALEC/ALEC.py", line 488, in main
>     cor_reads = correct_reads(reads)
>   File "/Users/bilcag/ALEC-master/ALEC/ALEC.py", line 427, in correct_reads
>     mis_rate.append(1-allele_freq_lst[i]["ATCG".index(ref_seq[i])]-allele_freq_lst[i][4])
> ValueError: substring not found

I am waiting for your help!
